# Generated by Django 4.0.4 on 2022-05-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskill',
            name='Job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='skillCode',
            field=models.CharField(max_length=150, verbose_name='Skill Code'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='item',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='itemRef',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ref',
            field=models.CharField(max_length=150),
        ),
    ]
