# Generated by Django 4.0.4 on 2022-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_jobskill_job_alter_jobskill_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='item',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='itemRef',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
