# Generated by Django 4.0.4 on 2022-05-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_alter_skill_item_alter_skill_itemref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ref',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
