# Generated by Django 4.0.4 on 2022-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_skill_level_alter_skill_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskill',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
