# Generated by Django 4.0.4 on 2022-05-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_jobskill_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackSmithFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgSrc', models.TextField(blank=True, null=True)),
                ('attr', models.CharField(max_length=50, null=True)),
                ('weak', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='zone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.jobskill', verbose_name='Skill'),
        ),
        migrations.CreateModel(
            name='MonsterDrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.item')),
                ('baseMonster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.monster')),
            ],
        ),
        migrations.CreateModel(
            name='BlacksmithMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('baseItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.item')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.blacksmithformula')),
            ],
        ),
        migrations.AddField(
            model_name='blacksmithformula',
            name='itemResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.item'),
        ),
    ]
